name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: "1.12"

      - name: Install Doxygen & Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake
        run: cmake -B build -S . -DSTC_BUILD_DOCS=ON -DSTC_USE_FORMAT=OFF

      - name: Build Docs
        run: cmake --build build --target docs

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/docs/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
